services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mudra_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      PYTHONUNBUFFERED: "1"
    volumes:
      - ./backend:/app
      - ./backend/dataset:/app/dataset
      - ./backend/weights:/app/weights

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mudra_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - backend
